# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FIPE_MVVM_Challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FIPE_MVVM_Challenge
  pod 'Alamofire', '~> 5.2'

end
